// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSkFBgTPlUlP3XAjQx-Q7Jf2Hv6rzxOYI',
    appId: '1:331243296230:web:0cc9c4848bf52149d53227',
    messagingSenderId: '331243296230',
    projectId: 'car-wash-5f1ca',
    authDomain: 'car-wash-5f1ca.firebaseapp.com',
    storageBucket: 'car-wash-5f1ca.firebasestorage.app',
    measurementId: 'G-6X7SC019WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-IszuTT9b6yF8Tv8AGJPj8MJhmORG-mY',
    appId: '1:331243296230:android:47af9ff4eab0966dd53227',
    messagingSenderId: '331243296230',
    projectId: 'car-wash-5f1ca',
    storageBucket: 'car-wash-5f1ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZ1wqwGh5HeoTH4KgXimCestMPFPbxvU',
    appId: '1:331243296230:ios:338e708b64b9c189d53227',
    messagingSenderId: '331243296230',
    projectId: 'car-wash-5f1ca',
    storageBucket: 'car-wash-5f1ca.firebasestorage.app',
    iosBundleId: 'com.example.washingCar',
  );
}
